### ISSUE TITLE
Matching board version

### ISSUE THREAD

**Issue by Fredrikaaa** [esno/yoga-bios-unlock#21]
I got a message saying my board version did not match, even though it should.
My board version is SDK0J40709 WIN.
I suspect the row of question marks has something to do with it.

The unlock worked fine when I used --force. 

```
Run in read mode
Be aware that readmode temporarily changes value of port 0x72 to index 0xf7
board_version does not match (SDK0J40709 WIN   ��������������������������������)
Wrong device, aborting!
```

**Comment by esno** [comment]
Hi,

I saw that issue before in https://github.com/esno/yoga-bios-unlock/issues/4
I really don't know what's wrong here. Seems like the bios in use provides a too large character array that is not initialized properly. Can you please mention your bios version?

```
cat /sys/class/dmi/id/bios_version
```
Probably it's best if I trim this string after 15 characters which I don't like that much since DMI
should provide reasonable content
